[[constraint]]
  branch = "master"
  name = "github.com/mozillazg/go-unidecode"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/thoas/go-funk"

[prune]
  go-tests = true
  unused-packages = true
